//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class SystemSet
{
    public int id { get; set; }
    public int NianFen { get; set; }
    public System.DateTime BaoMingTimeStart { get; set; }
    public System.DateTime BaoMingTimeEnd { get; set; }
    public System.DateTime ZKZPrintTimeStart { get; set; }
    public System.DateTime BaoMing2TimeStart { get; set; }
    public System.DateTime BaoMing2TimeEnd { get; set; }
    public System.DateTime ZKZPrintTimeEnd { get; set; }
    public Nullable<System.DateTime> NoLoginTimeStart { get; set; }
    public Nullable<System.DateTime> NoLoginTimeEnd { get; set; }
}

public partial class t_parameter
{
    public int id { get; set; }
    public string paraGroupCode { get; set; }
    public string paraName { get; set; }
    public string paraValue { get; set; }
    public int paraSort { get; set; }
    public string paraRemark { get; set; }
    public bool paraDefault { get; set; }
}

public partial class t_Role
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public t_Role()
    {
        this.tb_admin = new HashSet<tb_admin>();
    }

    public string Role { get; set; }
    public string GangweiCodes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tb_admin> tb_admin { get; set; }
}

public partial class tb_admin
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_admin()
    {
        this.tb_userinfo = new HashSet<tb_userinfo>();
    }

    public string UserName { get; set; }
    public string PassWord { get; set; }
    public string Role { get; set; }
    public string IDCardPIC { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tb_userinfo> tb_userinfo { get; set; }
    public virtual t_Role t_Role { get; set; }
}

public partial class tb_gangwei
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_gangwei()
    {
        this.tb_xueke = new HashSet<tb_xueke>();
    }

    public int GangweiCode { get; set; }
    public string GangWeiName { get; set; }
    public bool bUsed { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tb_xueke> tb_xueke { get; set; }
}

public partial class tb_userinfo
{
    public int id { get; set; }
    public string UserName { get; set; }
    public string XingMing { get; set; }
    public string Birthday { get; set; }
    public string ShengYuanDi { get; set; }
    public string BiYeSchool { get; set; }
    public string AuditCode { get; set; }
    public string AuditFeedback { get; set; }
    public Nullable<int> XueKeCode { get; set; }
    public string XueLiCode { get; set; }
    public Nullable<System.DateTime> BiYeTime { get; set; }
    public string QuanRiZhi { get; set; }
    public string ZhuanYe { get; set; }
    public string ShiFanLei { get; set; }
    public string ZiGeZheng { get; set; }
    public string DuSheng { get; set; }
    public string Mobile { get; set; }
    public string ZiGeZhengCode { get; set; }
    public string Address { get; set; }
    public string Tel { get; set; }
    public string XueQianWork { get; set; }
    public string BiYeZhengShuCode { get; set; }
    public string SexCode { get; set; }
    public string PTHLevel { get; set; }
    public string PTHZSNo { get; set; }
    public string IDPhoto { get; set; }
    public string MinZuCode { get; set; }
    public string PoliticalOrientationCode { get; set; }
    public string ZhiYeCode { get; set; }
    public System.DateTime CreateDT { get; set; }
    public string picResidenceBooklet { get; set; }
    public string picDiploma { get; set; }
    public string picArchiveCertificate { get; set; }
    public string picZiGeZheng { get; set; }
    public string picPTH { get; set; }
    public string picNewGraduates { get; set; }
    public string picKindergartenCommitment { get; set; }

    public virtual tb_xueke tb_xueke { get; set; }
    public virtual tb_admin tb_admin { get; set; }
}

public partial class tb_xueke
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_xueke()
    {
        this.tb_userinfo = new HashSet<tb_userinfo>();
    }

    public int XueKeCode { get; set; }
    public string XueKeName { get; set; }
    public int GangWeiCode { get; set; }
    public string kskmCode { get; set; }

    public virtual tb_gangwei tb_gangwei { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tb_userinfo> tb_userinfo { get; set; }
}

public partial class tb_zunkaozheng
{
    public string zkzCode { get; set; }
    public string UserName { get; set; }
    public string zuoweiCode { get; set; }
    public string kaoDian { get; set; }
    public string publicSubject { get; set; }
    public string privateSubject { get; set; }
    public string kaoShiTime { get; set; }
    public string kaoShiDate { get; set; }
    public string shiChangCode { get; set; }
    public string kaoDian1 { get; set; }
    public string shiChangCode1 { get; set; }
    public string zuoweiCode1 { get; set; }
    public string kaoShiDate1 { get; set; }
    public string kaoShiTime1 { get; set; }
}
