//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class teacherBaoMing_Entities : DbContext
{
    public teacherBaoMing_Entities()
        : base("name=teacherBaoMing_Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tb_gangwei> tb_gangwei { get; set; }
    public virtual DbSet<tb_xueke> tb_xueke { get; set; }
    public virtual DbSet<SystemSet> SystemSets { get; set; }
    public virtual DbSet<t_parameter> t_parameter { get; set; }
    public virtual DbSet<tb_zunkaozheng> tb_zunkaozheng { get; set; }
    public virtual DbSet<tb_userinfo> tb_userinfo { get; set; }
    public virtual DbSet<tb_admin> tb_admin { get; set; }
    public virtual DbSet<t_Role> t_Role { get; set; }
}
